### ISSUE TITLE
TnH map does not work while using TakeAndHoldTweaker

### ISSUE THREAD

**Issue by GnJake** [devyndamonster/TakeAndHoldTweaker#97] opened 2022-04-08 21:25 UTC
The map does not have any markers on it while tweaker is installed
![20220408171401_1](https://user-images.githubusercontent.com/67350366/162533248-2b53e63a-60bd-4ed7-9b44-fb2abc1df52e.jpg)
Vanilla ^^
![20220408171605_1](https://user-images.githubusercontent.com/67350366/162533296-8169424f-167d-4f84-a25f-824e5b297dc5.jpg)
With Tweaker ^^
![20220408171831_1](https://user-images.githubusercontent.com/67350366/162533524-e5dbafe9-baa2-45a7-92a0-f1f48256c423.jpg)
Same mod list but without Tweaker 
https://clips.twitch.tv/KawaiiSmokyPhoneTBTacoLeft-4q8t-IkHy1k6681g
Map being broken for swagger the other day
P.S, he never got it to work until he used vanilla, pretty sure the no markers is this mod but the other stuff is probably ovr

**Comment by devyndamonster** [comment] 2022-04-08 21:28
Duplicate of issue #94 , but basically on version 1.7.5 you must be on the alpha, or you can use version 1.7.4 on the main branch

**Closed as completed by devyndamonster** 2022-04-08 21:28 UTC

**Comment by GnJake** [comment] 2022-04-08 22:35
> Duplicate of issue #94 , but basically on version 1.7.5 you must be on the alpha, or you can use version 1.7.4 on the main branch

mb didn't see that one, will just switch to 1.7.4
